-- MySQL Script generated by MySQL Workbench
-- Tue Aug 29 13:25:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vinit_core_java_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vinit_core_java_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vinit_core_java_project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vinit_core_java_project` ;

-- -----------------------------------------------------
-- Table `vinit_core_java_project`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vinit_core_java_project`.`users` ;

CREATE TABLE IF NOT EXISTS `vinit_core_java_project`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `email_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 115
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinit_core_java_project`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vinit_core_java_project`.`tasks` ;

CREATE TABLE IF NOT EXISTS `vinit_core_java_project`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task` VARCHAR(45) NULL DEFAULT NULL,
  `task_status` VARCHAR(45) NULL DEFAULT NULL,
  `completed_at` DATETIME NULL DEFAULT NULL,
  `is_deleted` TINYINT(1) NULL DEFAULT '0',
  `user_id` INT NULL DEFAULT '101',
  PRIMARY KEY (`id`),
  INDEX `FK_USER_ID_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_USER_ID`
    FOREIGN KEY (`user_id`)
    REFERENCES `vinit_core_java_project`.`users` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
